### ISSUE TITLE
[Bounty] Contribute to Next.ID via Educational Video Intros or Articles

### ISSUE THREAD

**Issue by BinaryHB0916** [NextDotID/proof_server#52]
- Platform
    - [x]  Gitcoin
    - [x]  Next.ID
- Experience
    - [x]  Beginner
    - [ ]  Intermediate
    - [ ]  Advanced
- Category
    - [x]  Educational
    - [x]  Next.ID

### Action Items

Background: [Next.ID](http://next.id/) - Connect All Digital identities

Next.ID, the world’s first protocol offering Decentralized-Identity-as-a-Service (DIaaS), is a decentralized identity aggregation protocol that integrates all Web2 and Web3 digital identities, offering a comprehensive and verifiable identity database for open-source developers and projects to innovate and build dApps on.

Next.ID creates an identity infrastructure that securely aggregates users’ identities into Avatars, making it the primary touch point for interfacing with any app or dApp.

Operating as a DAO (Decentralized Autonomous Organization), Next.ID would always be run by the community. In order to call for the awareness of self-sovereign digital identities and enrich the development ecosystem, we’d like to generate more user-facing educational content in the format of videos or articles to help the masses (developers and potential social graph projects) to better understand Next.ID and what we are building (must include task 1, you can choose any of the tasks listed in 2 - 5):

1. What is Next.ID?
2. How can developers start building with Next.ID and what should the community expect in the long run to win together with the growth of the protocol?
3. Next.ID vs other DID protocols/projects: the difference and what makes Next.ID stand out uniquely.
4. The potential scope for a social-graph project to build upon/integrates with Next.ID.
5. What are the DID-related apps that can be built with Next.ID and other identity / social graph infrastructure?

**Desired submissions (we’re selecting 3 winners from all submissions):**

1. Video introductions to Next.ID (≥ 5 minutes, English, there is no need to show up faces)
2. Articles into Next.ID ((≥ 800 words, English)

Don’t hesitate to reach out to us before you start so the content you create has a better chance to win!

**Prizes for Videos:**

- 1st place: 400 USD
- 2nd place: 300 USD
- 3nd place：200 USD

**Prizes for Articles:**

- 1st place: 300 USD
- 1st place: 200 USD
- 1st place: 100 USD
++++
- Every participant who successfully makes a submission can get one OAT (on-chain achievement token) powered by Galxe! Collating certain amount of such OATs will get the hodlers to enjoy future benefits from the Next.ID DAO.

### **Resources**

Notion:

[https://nextid.notion.site/Next-ID-Home-0fb4ba9200d6458ab6c4fa81778f6a7b](https://www.notion.so/Next-ID-Home-0fb4ba9200d6458ab6c4fa81778f6a7b)

Docs:

[https://docs.next.id/](https://docs.next.id/)

GitHub:

[https://github.com/nextdotid/community](https://github.com/nextdotid/community)

Twitter:

[https://twitter.com/nextdotid](https://twitter.com/nextdotid)

Telegram:

[https://t.me/NextDotIDofficial](https://t.me/NextDotIDofficial)

Discord:

[https://discord.gg/tepa9K7E55](https://discord.gg/tepa9K7E55)

**Comment by bobsub218** [comment]
Can I still send my project?

**Comment by LindaMask** [comment]
> Can I still send my project?
yes

**Comment by HLABZcc** [comment]
🆔: https://github.com/HLABZcc/Next.ID

**Comment by bobsub218** [comment]
Explain NEXT.ID
https://github.com/bobsub218/NEXT_GUIDE
https://bobsub218.medium.com/next-id-79b99fa6c597
I created an online article and a pdf version on github, and also created images in png format that can be shared via social media.

**Comment by BinaryHB0916** [comment]
Thank you all for your participation. Results announced: https://twitter.com/NextDotID/status/1616011050033504258

Next.ID feels so grateful that you devote efforts to open source. See you at the next event!
